name: "release"

on:
    push:
        branches:
            - "main"

jobs:
    release:
        runs-on: "windows-latest"
        steps:
            -   uses: "actions/checkout@master"
                with:
                    ref: "main"
            -   uses: "actions/setup-node@master"
                with:
                    node-version: 10.13.0
            -   name: "Install dependencies"
                run: "npm install"
            -   name: "Build"
                run: "npm run electron:build"
            -   name: "ls"
                run: "cd releases && ls"
